[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[scheduled]
  [[scheduled.functions]]
    function = "counter"
    cron = "0 * * * *" # toutes les heures (change si nécessaire)
