[build]
  publish = "public"
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-scheduled"

# Cron job toutes les 30 secondes impossible (min = 1 min), donc on met 1 min
[[scheduled]]
  path = "/.netlify/functions/incrementCounter"
  schedule = "*/1 * * * *"
